export enum ProductType {
	CRUISER = 'CRUISER',
	SPORTBIKE = 'SPORTBIKE',
	NAKED = 'NAKED',
	TOURING = 'TOURING',
	ADVENTURE = 'ADVENTURE',
	DUAL_SPORT = 'DUAL_SPORT',
	MOTOCROSS = 'MOTOCROSS',
	SUPERMOTO = 'SUPERMOTO',
	RETRO = 'RETRO',
	SPORT_TOURING = 'SPORT_TOURING',
	SCRAMBLER = 'SCRAMBLER',
}

export enum ProductStatus {
	ACTIVE = 'ACTIVE',
	SOLD = 'SOLD',
	DELETE = 'DELETE',
}

export enum ProductLocation {
	SEOUL = 'SEOUL',
	BUSAN = 'BUSAN',
	INCHEON = 'INCHEON',
	DAEGU = 'DAEGU',
	GYEONGJU = 'GYEONGJU',
	GWANGJU = 'GWANGJU',
	CHONJU = 'CHONJU',
	DAEJON = 'DAEJON',
	JEJU = 'JEJU',
}
